apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_37cdd65a28505254a68de58cdcc6303b.name   }}
spec:
  type: {{ .Values.helm_service_37cdd65a28505254a68de58cdcc6303b.type }}
  ports:
    - port: {{ .Values.helm_service_37cdd65a28505254a68de58cdcc6303b.port }}
      targetPort: {{ .Values.helm_service_37cdd65a28505254a68de58cdcc6303b.target_port }}
      protocol: {{.Values.helm_service_37cdd65a28505254a68de58cdcc6303b.protocol}}
  {{- with .Values.helm_service_37cdd65a28505254a68de58cdcc6303b.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}